### ISSUE TITLE
ng-disabled not taking effect

### ISSUE THREAD

**Issue by jfrumar** [jeremypeters/ng-bs-animated-button#13]
I am initializing the button with `formIsInvalid: true`, but it's still active and can be clicked upon (despite having ng-disabled="true" on the button).

I'm using Angular 1.4.7.

**Comment by danilosetubal** [comment]
@jeremypeters Hi, could you please merge this fix?

**Comment by jeremypeters** [comment]
@danilosetubal I haven't got time at the moment to check it out and test - can you confirm the fix is good?

**Comment by danilosetubal** [comment]
@jeremypeters I just tested and everything looks good.

**Comment by jeremypeters** [comment]
Great stuff, thanks - that's been merged :+1:
